site_name: Guardiões da Saúde Docs
theme:
  palette:
    primary: teal
    accent: blue
  logo: ./assets/img/logo.png
  favicon: ./assets/img/favicon.ico
  name: material
  language: pt
extra_css:
  - assets/css/extra.css

dev_addr: "0.0.0.0:8000"